//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.MSTest.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp.MSTest.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sophia
        ///Jackson
        ///Emma
        ///Aiden
        ///Olivia
        ///Lucas
        ///Ava
        ///Liam
        ///Mia
        ///Noah
        ///Isabella
        ///Ethan
        ///Riley
        ///Mason
        ///Aria
        ///Caden
        ///Zoe
        ///Oliver
        ///Charlotte
        ///Elijah
        ///Lily
        ///Grayson
        ///Layla
        ///Jacob
        ///Amelia
        ///Michael
        ///Emily
        ///Benjamin
        ///Madelyn
        ///Carter
        ///Aubrey
        ///James
        ///Adalyn
        ///Jayden
        ///Madison
        ///Logan
        ///Chloe
        ///Alexander
        ///Harper
        ///Caleb
        ///Abigail
        ///Ryan
        ///Aaliyah
        ///Luke
        ///Avery
        ///Daniel
        ///Evelyn
        ///Jack
        ///Kaylee
        ///William
        ///Ella
        ///Owen
        ///Ellie
        ///Gabriel
        ///Scarlett
        ///Matthew
        ///Arianna
        ///Connor
        ///Hailey
        ///Jayce
        ///Nora
        ///Isaac
        ///Addison
        ///Sebastian
        ///Brooklyn
        ///Henry
        ///Hann [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH
        ///JOHNSON
        ///WILLIAMS
        ///BROWN
        ///JONES
        ///MILLER
        ///DAVIS
        ///GARCIA
        ///RODRIGUEZ
        ///WILSON
        ///MARTINEZ
        ///ANDERSON
        ///TAYLOR
        ///THOMAS
        ///HERNANDEZ
        ///MOORE
        ///MARTIN
        ///JACKSON
        ///THOMPSON
        ///WHITE
        ///LOPEZ
        ///LEE
        ///GONZALEZ
        ///HARRIS
        ///CLARK
        ///LEWIS
        ///ROBINSON
        ///WALKER
        ///PEREZ
        ///HALL
        ///YOUNG
        ///ALLEN
        ///SANCHEZ
        ///WRIGHT
        ///KING
        ///SCOTT
        ///GREEN
        ///BAKER
        ///ADAMS
        ///NELSON
        ///HILL
        ///RAMIREZ
        ///CAMPBELL
        ///MITCHELL
        ///ROBERTS
        ///CARTER
        ///PHILLIPS
        ///EVANS
        ///TURNER
        ///TORRES
        ///PARKER
        ///COLLINS
        ///EDWARDS
        ///STEWART
        ///FLORES
        ///MORRIS
        ///NGUYEN
        ///MURPHY
        ///RIVERA
        ///COOK
        ///ROGERS
        ///MORGAN
        ///PETERSON
        ///CO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
    }
}
